##########################################################
#                                                        #
#   PrefixBroadcast | Плагин на сообщения с префиксом.   #
#   Версия: 1.0                                          #
#   Гл. Разработчик: LUMIA | MoonLight Studio.           #
#   Специально для: Общего доступа.                      #
#   Сделано с любовью, спасибо, что выбрали -            #
#   Нас. MoonLight Studio - Исполняет мечты.             #
#   VK: https://vk.com/moonlightdevelopment              #
#   DA: https://www.donationalerts.com/r/lumiadev        #
#   Серер ДС: https://discord.gg/gb2kMFCDwG              #
#                                                        #
##########################################################

# Плагин поддерживает HEX цвета, и &. Так же - PlaceholderApi. Развлекайтесь на здоровье))
# В версии 1.2 добавлена поддержка MiniMessage

Messages:
  errorLenght: "&7Слишком мало аргументов! Пример использования: /pb all [LUMIA] Привет!" # | Ошибка аргументов.
  errorConsole: "Хи, консоль не может использовать команду /pb only, радиуса то нет)" # | Ошибка радиуса консоли.
  messageReload: "%player_name% <gradient:#FB08B3:#BC2EEF>Плагин перезагружен!</gradient>" # | Сообщение перезагрузки

Settings:
  onlyBlock: 10 # | На какие блоки распростроняется
  playerPermission: "pb.player" # | Пермишн, кто может видеть глобальное сообщение.
